SELECT *FROM BANK_DEPOSIT

ALTER TABLE BANK_DEPOSIT ALTER COLUMN PINCODE BIGINT; 

ALTER TABLE BANK_DEPOSIT DROP COLUMN ACCOUNT_TYPE;

SP_RENAME 'BANK_DEPOSIT.AMOUNT', 'BALANC';

ALTER TABLE DEPOSIT_DETAIL ADD STATUS VARCHAR(10);

SP_RENAME 'DEPOSIT_DETAIL' , 'BANK_DEPOSIT'