CREATE DATABASE  CSE_3A_209


CREATE TABLE STUDENT(
STDID INT,
SNAME VARCHAR(50),
CITY VARCHAR(50),
SPI DECIMAL(4,2),
BRANCH VARCHAR(50)
)

INSERT INTO STUDENT VALUES
(101 , 'HETVI' , 'RAJKOT' , 7.40, 'COMPUTER'),
(102 , 'RAJ' ,  'MORBI' , 9.50 , 'MECHANICAL' ),
(103 , 'VISHAL' ,  'RAJKOT' ,9.00 ,'CIVIL'),
(104 ,'DEEP' ,'SURAT' ,8.80 ,'COMPUTER'),
(105 ,'DHARMIK' ,'BARODA' ,8.80 ,'CHEMICAL'),
(106 ,'KRUNAL' ,'VAPI' ,9.00 ,'CIVIL'),
(107 ,'RIYA' ,'NAVSARI' ,5.50 ,'COMUTER'),
(108 ,'VRUNDA' ,'KUTCH' ,7.60, 'ELECRICAL'),
(109, 'SMAIR' , 'JAMNAGAR' , 6.80 ,'ES'),
(110 ,'PARAG', 'SURAT' ,7.00 ,'CHEMICAL'),
(111 ,'HARCH', 'RAJKOT' ,4.00, NULL)

SELECT *FROM STUDENT

SELECT SNAME , CITY FROM STUDENT

SELECT * FROM STUDENT WHERE BRANCH = 'COMPUTER';

SELECT * FROM STUDENT WHERE STDID <105

SELECT SNAME,CITY,SPI FROM STUDENT WHERE SPI >6.50 

SELECT SNAME,BRANCH,SPI FROM STUDENT WHERE SPI >8.00 AND BRANCH = 'COMPUTER'

SELECT SNAME,CITY,STDID FROM STUDENT WHERE STDID > 103 AND CITY = 'RAJKOT'

SELECT SNAME,CITY FROM STUDENT WHERE CITY = 'RAJKOT' OR CITY = 'SURAT'

SELECT SNAME,STDID,BRANCH,SPI FROM STUDENT WHERE SPI >8.0 AND STDID <105 

SELECT *FROM STUDENT WHERE SPI >= 7.0 AND SPI <= 9.0;

SELECT *FROM STUDENT WHERE SPI BETWEEN  7.0 AND  9.0;

SELECT * FROM STUDENT WHERE NOT BRANCH = 'COMPUTER';

SELECT * FROM STUDENT WHERE BRANCH = 'COMPUTER' OR BRANCH = 'CIVIL' OR BRANCH = 'CHEMICAL' AND STDID <104

SELECT * FROM STUDENT WHERE BRANCH != 'COMPUTER' AND BRANCH != 'CIVIL'

SELECT SNAME FROM STUDENT WHERE NOT SNAME = 'DEEP';

SELECT * FROM STUDENT WHERE BRANCH IS NULL;

SELECT DISTINCT BRANCH FROM STUDENT;

SELECT TOP 50 PERCENT *FROM STUDENT;

SELECT TOP 5  *FROM STUDENT;

