--From the table STUDENT perform the following queries:  

-------------------------------------Part – A:------------------------------------- 

SELECT * FROM STUDENT
--1. Display the details of students whose SPI is greater than the average SPI. 

SELECT SNAME,PERFORMANCE FROM STUDENT
WHERE PERFORMANCE > (SELECT AVG(PERFORMANCE) FROM STUDENT)

--2. Display the names of students whose SPI is less than the average SPI. 

SELECT SNAME,PERFORMANCE FROM STUDENT
WHERE PERFORMANCE < (SELECT AVG(PERFORMANCE) FROM STUDENT)

--3. Display the student details who has the highest SPI. 

SELECT * FROM STUDENT
WHERE PERFORMANCE = (SELECT MAX(PERFORMANCE) FROM STUDENT)

--4. Display the student details who has the lowest SPI.

SELECT * FROM STUDENT
WHERE PERFORMANCE = (SELECT MIN(PERFORMANCE) FROM STUDENT)

--5. Display the students whose SPI is greater than SPI of student DHARMIK. 

SELECT * FROM STUDENT
WHERE PERFORMANCE > (SELECT (PERFORMANCE) FROM STUDENT WHERE SNAME = 'DHARMIK')

--6. Display the students whose SPI is less than SPI of student RIYA. 

SELECT * FROM STUDENT
WHERE PERFORMANCE < (SELECT (PERFORMANCE) FROM STUDENT WHERE SNAME = 'RIYA')

--7. Display the students who belong to the same branch as KRUNAL. 

SELECT * FROM STUDENT
WHERE BRANCH = (SELECT (BRANCH) FROM STUDENT WHERE SNAME = 'KRUNAL')

--8. Display the students whose branch is different from HETVI. 


SELECT * FROM STUDENT
WHERE BRANCH != (SELECT (BRANCH) FROM STUDENT WHERE SNAME = 'HETVI')

--9. Display the second highest SPI from RESULT table.

SELECT MAX(SPI) FROM RESULT
WHERE SPI < (SELECT MAX(SPI)  FROM RESULT)

--10. Display the second lowest SPI from RESULT table. 

SELECT MIN(SPI) FROM RESULT
WHERE SPI > (SELECT MIN(SPI) FROM RESULT)

--11. Display the names of students whose SPI is above branch-wise average SPI.  

SELECT SNAME FROM STUDENT AS A
WHERE PERFORMANCE > (SELECT AVG(PERFORMANCE) FROM STUDENT AS S1 
WHERE S1.BRANCH = A.BRANCH)

--12. Display the branch having maximum average SPI.  

SELECT BRANCH, AVG(PERFORMANCE)
FROM STUDENT
GROUP BY BRANCH
HAVING AVG(PERFORMANCE) = (SELECT MAX(PERFORMANCE)FROM STUDENT)


--13. Display the branch having minimum average SPI. 

SELECT BRANCH, AVG(PERFORMANCE)
FROM STUDENT
GROUP BY BRANCH
HAVING AVG(PERFORMANCE) = (SELECT MIN(PERFORMANCE)FROM STUDENT)

--From the table STUDENT_INFO and RESULT perform the following queries:  

SELECT * FROM STUDENTINFO
SELECT * FROM RESULT
-------------------------------------Part – B:------------------------------------- 

--14. Display the students whose SPI is greater than all students of ME branch.  

SELECT * FROM STUDENTINFO s
JOIN RESULT R
ON S.RNO = R.RNO
WHERE  SPI > all (SELECT SPI
FROM STUDENTINFO S
JOIN RESULT R
ON S.RNO = R.RNO WHERE S.BRANCH = 'ME')
----------------------------- PART – B -----------------------------

--15. DISPLAY THE STUDENTS WHOSE SPI IS LESS THAN ANY STUDENT OF ME BRANCH.
SELECT * FROM STUDENTINFO S
JOIN RESULT R ON S.RNO = R.RNO
WHERE SPI < ANY (SELECT SPI
                 FROM STUDENTINFO S
                 JOIN RESULT R ON S.RNO = R.RNO
                 WHERE S.BRANCH = 'ME');

--16. DISPLAY THE STUDENT DETAILS WHOSE SPI IS NOT EQUAL TO ANY SPI OF EC BRANCH STUDENTS.
SELECT * FROM STUDENTINFO S
JOIN RESULT R ON S.RNO = R.RNO
WHERE SPI NOT IN (SELECT SPI
                  FROM STUDENTINFO S
                  JOIN RESULT R ON S.RNO = R.RNO
                  WHERE S.BRANCH = 'EC');

--17. DISPLAY THE NAMES OF STUDENTS WHO SCORED HIGHER SPI THAN STUDENT OF RNO 103.
SELECT S.SNAME
FROM STUDENTINFO S
JOIN RESULT R ON S.RNO = R.RNO
WHERE R.SPI > (SELECT SPI FROM RESULT WHERE RNO = 103);

--18. DISPLAY THE STUDENTS WHOSE SPI IS GREATER THAN AVERAGE SPI OF THEIR OWN BRANCH.
SELECT S.SNAME, S.BRANCH, R.SPI
FROM STUDENTINFO S
JOIN RESULT R ON S.RNO = R.RNO
WHERE R.SPI > (SELECT AVG(R1.SPI)
               FROM STUDENTINFO S1
               JOIN RESULT R1 ON S1.RNO = R1.RNO
               WHERE S1.BRANCH = S.BRANCH);

--19. DISPLAY THE STUDENTS WHOSE SPI IS GREATER THAN THE AVERAGE SPI OF CE BRANCH BUT GREATER THAN THE MAXIMUM SPI OF ME BRANCH.
SELECT S.SNAME, R.SPI
FROM STUDENTINFO S
JOIN RESULT R ON S.RNO = R.RNO
WHERE R.SPI > (SELECT AVG(R1.SPI)
               FROM STUDENTINFO S1
               JOIN RESULT R1 ON S1.RNO = R1.RNO
               WHERE S1.BRANCH = 'CE')
  AND R.SPI > (SELECT MAX(R2.SPI)
               FROM STUDENTINFO S2
               JOIN RESULT R2 ON S2.RNO = R2.RNO
               WHERE S2.BRANCH = 'ME');

--20. DISPLAY THE BRANCH NAMES WHOSE AVERAGE SPI IS GREATER THAN THE OVERALL AVERAGE SPI.
SELECT S.BRANCH, AVG(R.SPI) AS AVG_SPI
FROM STUDENTINFO S
JOIN RESULT R ON S.RNO = R.RNO
GROUP BY S.BRANCH
HAVING AVG(R.SPI) > (SELECT AVG(SPI) FROM RESULT);

--21. DISPLAY THE STUDENTS WHO HAVE MAXIMUM SPI IN THEIR RESPECTIVE BRANCH.
SELECT S.SNAME, S.BRANCH, R.SPI
FROM STUDENTINFO S
JOIN RESULT R ON S.RNO = R.RNO
WHERE R.SPI = (SELECT MAX(R1.SPI)
               FROM STUDENTINFO S1
               JOIN RESULT R1 ON S1.RNO = R1.RNO
               WHERE S1.BRANCH = S.BRANCH);

--22. DISPLAY THE STUDENTS WHOSE SPI IS GREATER THAN THEIR AVERAGE SPI OF THEIR BRANCH AND GREATER THAN OVERALL AVERAGE SPI.
SELECT S.SNAME, S.BRANCH, R.SPI
FROM STUDENTINFO S
JOIN RESULT R ON S.RNO = R.RNO
WHERE R.SPI > (SELECT AVG(R1.SPI)
               FROM STUDENTINFO S1
               JOIN RESULT R1 ON S1.RNO = R1.RNO
               WHERE S1.BRANCH = S.BRANCH)
  AND R.SPI > (SELECT AVG(SPI) FROM RESULT);


----------------------------- PART – C -----------------------------

--23. DISPLAY THE STUDENTS WHOSE SPI IS GREATER THAN AT LEAST ONE STUDENT OF EVERY BRANCH.
SELECT S.SNAME, R.SPI
FROM STUDENTINFO S
JOIN RESULT R ON S.RNO = R.RNO
WHERE R.SPI > ALL (SELECT MIN(R1.SPI)
                   FROM STUDENTINFO S1
                   JOIN RESULT R1 ON S1.RNO = R1.RNO
                   GROUP BY S1.BRANCH);

--24. DISPLAY THE STUDENTS WHOSE SPI IS LESS THAN ALL STUDENTS OF CE BRANCH.
SELECT S.SNAME, R.SPI
FROM STUDENTINFO S
JOIN RESULT R ON S.RNO = R.RNO
WHERE R.SPI < ALL (SELECT R1.SPI
                   FROM STUDENTINFO S1
                   JOIN RESULT R1 ON S1.RNO = R1.RNO
                   WHERE S1.BRANCH = 'CE');

--25. DISPLAY THE BRANCH THAT CONTAINS THE STUDENT WITH HIGHEST SPI.
SELECT S.BRANCH
FROM STUDENTINFO S
JOIN RESULT R ON S.RNO = R.RNO
WHERE R.SPI = (SELECT MAX(SPI) FROM RESULT);

--26. DISPLAY THE STUDENTS WHOSE SPI IS LESS THAN THE SPI OF EVERY STUDENT IN CE BRANCH AND GREATER THAN EVERY STUDENT IN ME BRANCH.
SELECT S.SNAME, R.SPI
FROM STUDENTINFO S
JOIN RESULT R ON S.RNO = R.RNO
WHERE R.SPI < ALL (SELECT R1.SPI
                   FROM STUDENTINFO S1
                   JOIN RESULT R1 ON S1.RNO = R1.RNO
                   WHERE S1.BRANCH = 'CE')
  AND R.SPI > ALL (SELECT R2.SPI
                   FROM STUDENTINFO S2
                   JOIN RESULT R2 ON S2.RNO = R2.RNO
                   WHERE S2.BRANCH = 'ME');
