
--16. Copy records with NULL branch into NULL_BRANCH_STUDENTS. 

SELECT * INTO NULL_BRANCH_STUDENTS
FROM STUDENT
WHERE BRANCH IS NULL
SELECT * FROM NULL_BRANCH_STUDENTS

--17. Copy all STUDENT records and rename SPI as PERFORMANCE into STUDENT_COPY.
SP_RENAME 'STUDENT.SPI','PERFORMANCE'
SELECT * INTO STUDENT_COPY
FROM STUDENT
SELECT * FROM STUDENT_COPY

--18. Copy records where CITY in ('RAJKOT','SURAT') into CITY_WISE.

SELECT * INTO CITY_WISE
FROM STUDENT
WHERE CITY IN ('RAJKOT','SURAT')
SELECT * FROM CITY_WISE

--19. Copy students where BRANCH <> 'CIVIL' into NON_CIVIL_STUDENTS.  

SELECT * INTO NON_CIVIL_STUDENTS
FROM STUDENT
WHERE BRANCH <> 'CIVIL'
SELECT * FROM NON_CIVIL_STUDENTS

--20. Copy selected columns (SNAME, CITY) from STUDENT table into a new table.

SELECT SNAME,CITY INTO NEW_TABLE1
FROM STUDENT
SELECT * FROM NEW_TABLE1