


--1. Copy all records from DEPOSIT where AMOUNT > 3000 into HIGH_AMOUNT.  

SELECT * INTO HIGH_AMOUNT 
FROM DEPOSIT
WHERE AMOUNT > 3000
SELECT * FROM HIGH_AMOUNT

--2. Copy only CNAME and AMOUNT from DEPOSIT where BNAME = 'MAVDI' into MAVDI_CUSTOMERS.  

SELECT CNAME , AMOUNT INTO MAVDI_CUSTOMERS 
FROM DEPOSIT 
WHERE BNAME = 'MAVDI' 
SELECT * FROM MAVDI_CUSTOMERS

--3. Copy records of DEPOSIT where ADATE > '2025-01-01' into RECENT_DEPOSITS.  

SELECT * INTO RECENT_DEPOSITS
FROM DEPOSIT
WHERE ADATE >'2025-01-01'
SELECT * FROM RECENT_DEPOSITS


--4. Copy distinct BNAME from DEPOSIT into BRANCH_LIST.  

SELECT DISTINCT BNAME
INTO BRANCH_LIST
FROM DEPOSIT
SELECT * FROM BRANCH_LIST

--5. Copy top 5 records from DEPOSIT into TOP_DEPOSITS.  

SELECT TOP 5 * INTO TOP_DEPOSITS
FROM DEPOSIT
SELECT * FROM TOP_DEPOSITS

--6. Copy records where AMOUNT between 2000 and 6000 into MID_RANGE.  

SELECT * INTO MID_RNAME
FROM DEPOSIT
WHERE AMOUNT BETWEEN 2000 AND 6000
SELECT * FROM MID_RNAME

--7. Copy distinct branch names from DEPOSIT into UNIQUE_BRANCH. 

SELECT DISTINCT BNAME
INTO UNIQUE_BRANCH
FROM DEPOSIT
SELECT * FROM UNIQUE_BRANCH

--8. Copy records with NULL branch into NO_BRANCH_ASSIGNED.  

SELECT * INTO NO_BRANCH_ASSIGNED
FROM DEPOSIT
WHERE BNAME IS NULL
SELECT * FROM NO_BRANCH_ASSIGNED


--9. Copy all records and rename AMOUNT as BALANCE into DEPOSIT_COPY.  

SP_RENAME 'DEPOSIT.AMOUNT','BALANCE'
SELECT * INTO DEPOSIT_COPY
FROM DEPOSIT
SELECT * FROM DEPOSIT_COPY

--10. Copy records where BNAME in ('MAVDI','BEDI') into SELECTED_BRANCH. 

SELECT * INTO SELECTED_BRANCH
FROM DEPOSIT
WHERE BNAME = 'MAVDI' OR BNAME = 'BEDI'
SELECT * FROM SELECTED_BRANCH