
--11. Create a new table STUDENT_BACKUP from STUDENT without copying any data. 

SELECT * INTO STUDENT_BACKUP
FROM STUDENT
WHERE 1=0
SELECT * FROM STUDENT_BACKUP

--12. Copy SNAME and CITY where BRANCH = 'COMPUTER' into CS_STUDENTS.  

SELECT SNAME , CITY INTO CS_STUDENTS
FROM STUDENT
WHERE BRANCH = 'COMPUTER'
SELECT * FROM CS_STUDENTS

--13. Copy top 3 students based on SPI into TOPPER_LIST. 

SELECT TOP 3 * INTO TOPPER_LIST
FROM STUDENT
ORDER BY SPI DESC
SELECT * FROM TOPPER_LIST

--14. Copy distinct CITY from STUDENT into CITY_LIST. 

SELECT DISTINCT CITY INTO CITY_LIST
FROM STUDENT
SELECT * FROM CITY_LIST

--15. Copy records where STDID between 103 and 108 into MID_STUDENTS. 

SELECT * INTO MID_STUDENTS
FROM STUDENT
WHERE STDID BETWEEN 103 AND 108
SELECT * FROM MID_STUDENTS