--From the table STADIUM, TEAM and PLAYER perform the following queries:  

--------------------------Part – A:----------------------------

SELECT * FROM STADIUM
SELECT * FROM TEAM
SELECT * FROM PLAYER

--1. Display players who belong to teams located in ‘Mumbai’. 

SELECT P.PLAYER_FIRST_NAME,P.PLAYER_LAST_NAME,S.Stadium_city
FROM PLAYER P
JOIN TEAM T
ON P.TEAM_ID = T.TEAM_ID

JOIN STADIUM S
ON S.Stadium_id = T.HOME_STADIUM_ID

WHERE Stadium_city = 'Mumbai'

--2. Display all teams and players. 

SELECT T.TEAM_NAME,P.PLAYER_ID
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID

--3. Display players along with team wins and stadium city. 

SELECT P.PLAYER_FIRST_NAME,P.PLAYER_LAST_NAME,T.TEAM_WINS,S.Stadium_city
FROM PLAYER P
JOIN TEAM T
ON P.TEAM_ID = T.TEAM_ID

JOIN STADIUM S
ON T.HOME_STADIUM_ID = S.Stadium_id

--4. Display team name and number of players in each team. 

SELECT T.TEAM_NAME ,COUNT(P.PLAYER_ID)
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME

--5. Display team name, coach, and number of bowlers in each team. 

SELECT T.TEAM_NAME,T.TEAM_COACH,COUNT(P.PLAYER_ID)
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
WHERE P.PLAYER_ROLE='Bowler'
GROUP BY T.TEAM_NAME,T.TEAM_COACH

--6. Display team name with count of batsmen, bowlers, and all-rounders. 

SELECT T.TEAM_NAME, SUM(CASE WHEN P.PLAYER_ROLE = 'Batsman' THEN 1 ELSE 0 END) AS BATSMEN,
SUM(CASE WHEN P.PLAYER_ROLE = 'Bowler' THEN 1 ELSE 0 END) AS BOWLERS,
SUM(CASE WHEN P.PLAYER_ROLE = 'All-rounder' THEN 1 ELSE 0 END) AS ALLrounders
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME

--7. Display stadiums where teams have won more than 10 matches.

SELECT S.Stadium_city,T.TEAM_WINS,T.TEAM_NAME
FROM STADIUM S
JOIN TEAM T
ON S.Stadium_id = T.HOME_STADIUM_ID
WHERE T.TEAM_WINS > 10

--8. Display team name and number of players whose matches played is greater than 25. 

SELECT T.TEAM_NAME,COUNT(P.PLAYER_MATCHES_PLAYED)
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
WHERE P.PLAYER_MATCHES_PLAYED > 25
GROUP BY T.TEAM_NAME

--9. Display team name and total number of players having jersey number greater than 30. 

SELECT T.TEAM_NAME,P.PLAYER_FIRST_NAME,P.PLAYER_LAST_NAME,COUNT(P.PLAYER_JERSEY_NUMBER) AS jersey_number_greater_than_30
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
WHERE P.PLAYER_JERSEY_NUMBER > 30
GROUP BY T.TEAM_NAME,P.PLAYER_FIRST_NAME,P.PLAYER_LAST_NAME

--10. Display team name and total matches played by its players.

SELECT T.TEAM_NAME,SUM(P.PLAYER_MATCHES_PLAYED) AS total_matches_played_by_its_players
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME

----------------------------Part – B:--------------------------

--11. Display stadium city and total number of teams in each city.

SELECT S.Stadium_city,SUM(T.TEAM_ID)
FROM STADIUM S
JOIN TEAM T
ON S.Stadium_id = T.HOME_STADIUM_ID
GROUP BY S.Stadium_city
----------------------------- PART – B -----------------------------

--12. DISPLAY TEAM NAME AND AVERAGE MATCHES PLAYED BY PLAYERS IN EACH TEAM.
SELECT T.TEAM_NAME, AVG(P.PLAYER_MATCHES_PLAYED) AS AVG_MATCHES
FROM TEAM T
JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME;

--13. DISPLAY TEAM NAME AND MAXIMUM MATCHES PLAYED BY ANY PLAYER IN EACH TEAM.
SELECT T.TEAM_NAME, MAX(P.PLAYER_MATCHES_PLAYED) AS MAX_MATCHES
FROM TEAM T
JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME;

--14. DISPLAY TEAM NAME AND MINIMUM MATCHES PLAYED BY ANY PLAYER IN EACH TEAM.
SELECT T.TEAM_NAME, MIN(P.PLAYER_MATCHES_PLAYED) AS MIN_MATCHES
FROM TEAM T
JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME;

--15. DISPLAY STADIUM NAME AND TOTAL NUMBER OF PLAYERS PLAYING UNDER TEAMS OF THAT STADIUM.
SELECT S.STADIUM_NAME, COUNT(P.PLAYER_ID) AS TOTAL_PLAYERS
FROM STADIUM S
JOIN TEAM T ON S.STADIUM_ID = T.HOME_STADIUM_ID
JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
GROUP BY S.STADIUM_NAME;


----------------------------- PART – C -----------------------------

--16. DISPLAY TEAMS HAVING MORE ALL-ROUNDERS THAN BOWLERS.
SELECT T.TEAM_NAME
FROM TEAM T
JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME
HAVING SUM(CASE WHEN P.PLAYER_ROLE = 'All-rounder' THEN 1 ELSE 0 END) >
       SUM(CASE WHEN P.PLAYER_ROLE = 'Bowler' THEN 1 ELSE 0 END);

--17. DISPLAY TEAMS WHERE DIFFERENCE BETWEEN MAX AND MIN PLAYER MATCHES IS GREATER THAN 5.
SELECT T.TEAM_NAME
FROM TEAM T
JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME
HAVING MAX(P.PLAYER_MATCHES_PLAYED) - MIN(P.PLAYER_MATCHES_PLAYED) > 5;

--18. DISPLAY STADIUM CITY AND TOTAL WINS OF TEAMS IN THAT CITY.
SELECT S.STADIUM_CITY, SUM(T.TEAM_WINS) AS TOTAL_WINS
FROM STADIUM S
JOIN TEAM T ON S.STADIUM_ID = T.HOME_STADIUM_ID
GROUP BY S.STADIUM_CITY;

--19. DISPLAY TEAM NAME AND TOTAL NUMBER OF PLAYERS FOR EACH ROLE (GROUPED BY ROLE).
SELECT T.TEAM_NAME, P.PLAYER_ROLE, COUNT(P.PLAYER_ID) AS TOTAL_PLAYERS
FROM TEAM T
JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME, P.PLAYER_ROLE;

--20. DISPLAY TEAM NAME AND TOTAL NUMBER OF PLAYERS WHOSE NAME STARTS WITH ‘A’.
SELECT T.TEAM_NAME, COUNT(P.PLAYER_ID) AS TOTAL_PLAYERS_STARTING_WITH_A
FROM TEAM T
JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
WHERE P.PLAYER_FIRST_NAME LIKE 'A%'
GROUP BY T.TEAM_NAME;
’ 