
--Part – A:

--1. Combine information from Person and Department table using cross join or Cartesian product. 

SELECT * FROM PERSON
CROSS JOIN Department;

--2. Find all persons with their department name 

SELECT PERSON.PersonID,PERSON.PersonName,DEPARTMENT.DepartmentName
FROM PERSON
INNER JOIN DEPARTMENT
ON PERSON.DepartmentID = DEPARTMENT.DepartmentID;

--3. Find all persons with their department name & code.

SELECT PERSON.DEPARTMENTID,PERSON.PERSONNAME,DEPARTMENT.DEPARTMENTCODE,DEPARTMENT.DEPARTMENTNAME
FROM PERSON
INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

--4. Find all persons with their department code and location. 

SELECT P.DEPARTMENTID,P.PERSONNAME,DEPARTMENT.DEPARTMENTCODE,DEPARTMENT.LOCATION
FROM PERSON P
INNER JOIN DEPARTMENT
ON P.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

--5. Find the detail of the person who belongs to Mechanical department.

SELECT P.PERSONID,P.PERSONNAME,D.DEPARTMENTNAME
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTNAME = 'MECHANICAL'

--6. Final person’s name, department code and salary who lives in Ahmedabad city.  

SELECT P.PERSONNAME,P.SALARY,DEPARTMENTCODE
FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE CITY = 'AHMEDABAD'

--7. Find the person's name whose department is in C-Block. 

SELECT P.PERSONNAME,P.SALARY,DEPARTMENTCODE
FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE LOCATION = 'C-BLOCK'

--8. Retrieve person name, salary & department name who belongs to Jamnagar city. 

SELECT P.PERSONNAME,P.SALARY,D.DEPARTMENTNAME
FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE CITY = 'JAMNAGAR'

--9. Retrieve person’s detail who joined the Civil department after 1-Aug-2001. 

SELECT *
FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE DEPARTMENTNAME = 'CIVIL' AND JOININGDATE > '1-08-2001'

--10. DISPLAY ALL THE PERSON'S NAME WITH THE DEPARTMENT WHOSE JOINING DATE DIFFERENCE WITH THE CURRENT DATE IS MORE THAN 25 YEARS.
SELECT P.PERSONNAME, D.DEPARTMENTNAME
FROM PERSON P
JOIN DEPARTMENT D 
ON P.DEPARTMENTID = D.DEPARTMENTID

--11. FIND DEPARTMENT WISE PERSON COUNTS.
SELECT D.DEPARTMENTNAME, COUNT(P.PERSONID) AS PERSON_COUNT
FROM PERSON P
JOIN DEPARTMENT D ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;

--12. GIVE DEPARTMENT WISE MAXIMUM & MINIMUM SALARY WITH DEPARTMENT NAME.

SELECT D.DEPARTMENTNAME, MAX(P.SALARY) AS MAXS, MIN(P.SALARY) AS MINS
FROM PERSON P
JOIN DEPARTMENT D ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;

--13. FIND CITY WISE TOTAL, AVERAGE, MAXIMUM AND MINIMUM SALARY.

SELECT P.CITY, SUM(P.SALARY) AS TOTALS, AVG(P.SALARY) AS AVGS,
MAX(P.SALARY) AS MAX_SALARY, MIN(P.SALARY) AS MIN_SALARY
FROM PERSON P
GROUP BY P.CITY;

--14. FIND THE AVERAGE SALARY OF A PERSON WHO BELONGS TO AHMEDABAD CITY.

SELECT AVG(P.SALARY) AS AVG_SALARY_AHMEDABAD
FROM PERSON P
WHERE P.CITY = 'AHMEDABAD';

----------------------------- PART – B -----------------------------

--16. PRODUCE OUTPUT LIKE: <PERSONNAME> EARNS <SALARY> FROM <DEPARTMENTNAME> DEPARTMENT MONTHLY. (IN SINGLE COLUMN)
SELECT PERSONNAME + ' EARNS ' + CAST(SALARY AS VARCHAR) + ' FROM ' + DEPARTMENTNAME + ' DEPARTMENT MONTHLY.' AS RESULT
FROM PERSON P
JOIN DEPARTMENT D ON P.DEPARTMENTID = D.DEPARTMENTID;

--17. FIND CITY & DEPARTMENT WISE TOTAL, AVERAGE & MAXIMUM SALARIES.
SELECT P.CITY, D.DEPARTMENTNAME,
       SUM(P.SALARY) AS TOTAL_SALARY,
       AVG(P.SALARY) AS AVG_SALARY,
       MAX(P.SALARY) AS MAX_SALARY
FROM PERSON P
JOIN DEPARTMENT D ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY P.CITY, D.DEPARTMENTNAME;

--18. FIND ALL PERSONS WHO DO NOT BELONG TO ANY DEPARTMENT.
SELECT PERSONID, PERSONNAME
FROM PERSON
WHERE DEPARTMENTID IS NULL;

--19. FIND ALL DEPARTMENTS WHOSE TOTAL SALARY IS EXCEEDING 100000.
SELECT D.DEPARTMENTNAME, SUM(P.SALARY) AS TOTAL_SALARY
FROM PERSON P
JOIN DEPARTMENT D ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING SUM(P.SALARY) > 100000;


----------------------------- PART – C -----------------------------

--20. LIST ALL DEPARTMENTS WHO HAVE NO PERSON.
SELECT D.DEPARTMENTNAME
FROM DEPARTMENT D
LEFT JOIN PERSON P ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE P.PERSONID IS NULL;

--21. LIST OUT DEPARTMENT NAMES IN WHICH MORE THAN TWO PERSONS ARE WORKING.
SELECT D.DEPARTMENTNAME, COUNT(P.PERSONID) AS PERSON_COUNT
FROM PERSON P
JOIN DEPARTMENT D ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING COUNT(P.PERSONID) > 2;

--22. GIVE A 10% INCREMENT IN THE COMPUTER DEPARTMENT EMPLOYEE’S SALARY. (USE UPDATE)
UPDATE PERSON
SET SALARY = SALARY * 1.10
WHERE DEPARTMENTID = (SELECT DEPARTMENTID FROM DEPARTMENT WHERE DEPARTMENTNAME = 'COMPUTER');
