USE CSE_3A_209

SELECT *FROM STUDENT

--Update SPI of all students from 7.00 to 8.00. 

UPDATE STUDENT SET SPI = 8.00 WHERE SPI = 7.00;

--Change city of HETVI from RAJKOT to AHMEDABAD. 

UPDATE STUDENT SET CITY = 'AHMEDABAD' WHERE CITY = 'RAJKOT'

--Update SPI of DEEP to 9.20 and city to VADODARA.

UPDATE STUDENT SET SPI = 9.20, CITY = 'VADODARA' WHERE SNAME = 'DEEP';

--Update SPI of DHARMIK to 8.50. 

UPDATE STUDENT SET SPI = 8.50 WHERE SNAME = 'DHARMIK'

--Update branch name from COMPUTER to IT.

UPDATE STUDENT SET BRANCH = 'IT' WHERE BRANCH = 'COMPUTER'

--Update branch of RAJ to AUTOMOBILE.

UPDATE STUDENT SET BRANCH = 'AUTOMOBILE' WHERE SNAME = 'RAJ'

--Update SPI to 7.50 where STDID is between 103 and 107.

UPDATE STUDENT SET SPI = 7.50 WHERE STDID BETWEEN 103 AND 107

 --Update city of PARAG to MUMBAI. 

 UPDATE STUDENT SET CITY = 'MUMBAI' WHERE CITY = 'PARAG'

 --Update SPI of RIYA to 6.00.
 
 UPDATE STUDENT SET SPI = 6.00 WHERE SNAME = 'RIYA'

 --Update SPI of SMAIR to 7.20 and branch to ELECTRICAL.
 
 UPDATE STUDENT SET SPI = 7.20 WHERE BRANCH = 'ELECTRICAL'