CREATE TABLE ONLINE_CUSTOMER
(
    CID INT,
    NAMEE VARCHAR(50),
    CITY VARCHAR(50)
);

INSERT INTO ONLINE_CUSTOMER VALUES
(101, 'RAHUL', 'RAJKOT'),
(103, 'PTIYA', 'SURAT'),
(106, 'DHARMIK', 'SURAT'),
(107, 'MEHUL', 'MORBI');
SELECT * FROM ONLINE_CUSTOMER

CREATE TABLE OFFLINE_CUSTOMER
(
    CID INT,
    NAMEE VARCHAR(50),
    CITY VARCHAR(50)
);

INSERT INTO OFFLINE_CUSTOMER VALUES
(102, 'AMIT', 'AHMEDABAD'),
(104, 'HETVI', 'BARODA'),
(105, 'RIYA', 'RAJKOT'),
(106, 'DHARMIK', 'SURAT');

CREATE TABLE CUSTOMER
(
    CID INT,
    NAMEE VARCHAR(50),
    CITY VARCHAR(50),
    MEMBERSHIP VARCHAR(20)
);

INSERT INTO CUSTOMER VALUES
(101, 'RAHUL', 'RAJKOT', 'GOLD'),
(102, 'AMIT', 'AHMEDABAD', 'SILVER'),
(103, 'PTIYA', 'SURAT', 'GOLD'),
(104, 'HETVI', 'BARODA', 'PLATINUM'),
(105, 'RIYA', 'RAJKOT', 'SILVER'),
(106, 'DHARMIK', 'SURAT', 'GOLD'),
(108, 'ISHITA', 'RAJOT', 'GOLD');

--From the above table perform the following queries:

---------------------------------Part – A:--------------------------------- 

--1. Display all unique customer names from ONLINE_CUSTOMER and OFFLINE_CUSTOMER. 

SELECT  NAMEE
FROM ONLINE_CUSTOMER
UNION
SELECT  NAMEE
FROM OFFLINE_CUSTOMER;


--2. Display all unique customer cities from ONLINE_CUSTOMER and OFFLINE_CUSTOMER. 

SELECT CITY
FROM ONLINE_CUSTOMER
UNION
SELECT CITY
FROM OFFLINE_CUSTOMER

--3. Display duplicate customer names from both tables ONLINE_CUSTOMER and OFFLINE_CUSTOMER. 

SELECT NAMEE
FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAMEE
FROM OFFLINE_CUSTOMER

--4. Display unique customer IDs from both tables. 

SELECT CID
FROM ONLINE_CUSTOMER
UNION
SELECT CID
FROM OFFLINE_CUSTOMER

--5. Display all GOLD membership customer names and online customer names using UNION. 

SELECT CID
FROM ONLINE_CUSTOMER
UNION
SELECT CID
FROM CUSTOMER
WHERE MEMBERSHIP = 'GOLD'

--6. Display all customer names from CUSTOMER and ONLINE_CUSTOMER using UNION. 

SELECT NAMEE
FROM CUSTOMER
UNION
SELECT NAMEE
FROM ONLINE_CUSTOMER

--7. Display all cities from CUSTOMER and OFFLINE_CUSTOMER using UNION.


SELECT CITY
FROM CUSTOMER
UNION
SELECT CITY
FROM OFFLINE_CUSTOMER

--8. Display all customer IDs from CUSTOMER and OFFLINE_CUSTOMER using UNION ALL. 

SELECT CID
FROM CUSTOMER
UNION ALL
SELECT CID
FROM OFFLINE_CUSTOMER

--9. Display all customer names from RAJKOT city using UNION. 

SELECT NAMEE
FROM CUSTOMER
WHERE CITY = 'RAJKOT'
UNION

SELECT NAMEE
FROM ONLINE_CUSTOMER
WHERE CITY = 'RAJKOT'
UNION 

SELECT NAMEE
FROM OFFLINE_CUSTOMER
WHERE CITY = 'RAJKOT'

--10. Display all customer names starting with R from both tables using UNION.

SELECT NAMEE
FROM ONLINE_CUSTOMER
WHERE NAMEE LIKE 'R%'

UNION 

SELECT NAMEE
FROM OFFLINE_CUSTOMER
WHERE NAMEE LIKE 'R%'

--11. Display customers who are both ONLINE and OFFLINE. 

SELECT *
FROM ONLINE_CUSTOMER
INTERSECT
SELECT *
FROM OFFLINE_CUSTOMER

--12. Display customer IDs existing in both ONLINE_CUSTOMER and OFFLINE_CUSTOMER. 

SELECT CID
FROM ONLINE_CUSTOMER
INTERSECT
SELECT CID
FROM OFFLINE_CUSTOMER

--13. Display customer names existing only in ONLINE_CUSTOMER. 

SELECT NAMEE
FROM ONLINE_CUSTOMER
EXCEPT
SELECT NAMEE
FROM OFFLINE_CUSTOMER

--14. Display customer names existing only in OFFLINE_CUSTOMER. 
SELECT NAMEE
FROM OFFLINE_CUSTOMER
EXCEPT
SELECT NAMEE
FROM ONLINE_CUSTOMER
--15. Display cities available in both ONLINE_CUSTOMER and OFFLINE_CUSTOMER. 

SELECT NAMEE
FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAMEE
FROM OFFLINE_CUSTOMER
 
---------------------------------Part – B: ---------------------------------

--16. Display customer names who are GOLD members and online customers.

SELECT NAMEE
FROM CUSTOMER
WHERE MEMBERSHIP = 'GOLD'
INTERSECT
SELECT NAMEE
FROM ONLINE_CUSTOMER

--17. Display customer names who are PLATINUM members but not online customers. 

SELECT NAMEE
FROM CUSTOMER
WHERE MEMBERSHIP = 'PLATINUM'
EXCEPT
SELECT NAMEE
FROM OFFLINE_CUSTOMER

--18. Display customer IDs who are online customers but not offline customers.

SELECT CID 
FROM ONLINE_CUSTOMER
EXCEPT
SELECT CID 
FROM OFFLINE_CUSTOMER;

--19. Display customer IDs who are offline customers but not online customers. 

SELECT CID 
FROM OFFLINE_CUSTOMER
EXCEPT
SELECT CID 
FROM ONLINE_CUSTOMER;

--20. Display customers who are present in CUSTOMER table but not in ONLINE_CUSTOMER. 


SELECT NAMEE
FROM CUSTOMER
EXCEPT
SELECT NAMEE
FROM ONLINE_CUSTOMER;

--21. Display customers who are both GOLD members and available in OFFLINE_CUSTOMER. 
SELECT NAMEE
FROM CUSTOMER
WHERE MEMBERSHIP = 'GOLD'
INTERSECT
SELECT NAMEE
FROM OFFLINE_CUSTOMER;


--22. Display all distinct cities from all three tables. 

SELECT CITY
FROM ONLINE_CUSTOMER
UNION

SELECT CITY
FROM OFFLINE_CUSTOMER
UNION

SELECT CITY
FROM CUSTOMER

--23. Display customers who are online customers and belong to SURAT city using INTERSECT. 

SELECT *
FROM ONLINE_CUSTOMER
INTERSECT
SELECT *
FROM ONLINE_CUSTOMER

WHERE CITY = 'SURAT'

--24. Display customers who are offline customers but not from RAJKOT city using MINUS

SELECT NAMEE FROM OFFLINE_CUSTOMER
EXCEPT
SELECT NAMEE FROM ONLINE_CUSTOMER
WHERE CITY = 'RAJKOT'

--25. Display customers who are GOLD members, online customers, and from SURAT city using INTERSECT. 

SELECT * FROM CUSTOMER
WHERE MEMBERSHIP = 'GOLD'
INTERSECT
SELECT * FROM ONLINE_CUSTOMER
WHERE CITY = 'SURAT'
 
----------------------------- PART – C -----------------------------

--26. DISPLAY CUSTOMER NAMES WHO ARE PRESENT IN AT LEAST TWO TABLES.
SELECT NAMEE
FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAMEE
FROM OFFLINE_CUSTOMER

--27. DISPLAY ALL CUSTOMER NAMES FROM CUSTOMER TABLE EXCLUDING CUSTOMERS AVAILABLE IN BOTH ONLINE_CUSTOMER AND OFFLINE_CUSTOMER.
SELECT NAMEE
FROM CUSTOMER
EXCEPT
(SELECT NAMEE
 FROM ONLINE_CUSTOMER
 INTERSECT
 SELECT NAMEE
 FROM OFFLINE_CUSTOMER);

--28. DISPLAY CUSTOMER NAMES WHO ARE PRESENT IN BOTH ONLINE_CUSTOMER AND OFFLINE_CUSTOMER  BUT NOT PLATINUM MEMBERS.
SELECT NAMEE
FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAMEE
FROM OFFLINE_CUSTOMER
EXCEPT
SELECT NAMEE
FROM CUSTOMER
WHERE MEMBERSHIP = 'PLATINUM';

--29. DISPLAY CUSTOMER NAMES WHO ARE EITHER ONLINE OR OFFLINE BUT NOT BOTH.
SELECT NAMEE
FROM ONLINE_CUSTOMER
EXCEPT
SELECT NAMEE
FROM OFFLINE_CUSTOMER
UNION
SELECT NAMEE
FROM OFFLINE_CUSTOMER
EXCEPT
SELECT NAMEE
FROM ONLINE_CUSTOMER;

--30. DISPLAY CUSTOMER IDS PRESENT IN CUSTOMER TABLE BUT MISSING FROM BOTH ONLINE_CUSTOMER AND OFFLINE_CUSTOMER.
SELECT CID
FROM CUSTOMER
EXCEPT
(SELECT CID FROM ONLINE_CUSTOMER
 UNION
 SELECT CID FROM OFFLINE_CUSTOMER);