--From the table STUDENT perform the following queries:

--Part – A:

SELECT * FROM STUDENT

--1. Display rank of students based on SPI.

SELECT STDID ,SNAME , CITY ,PERFORMANCE ,BRANCH , ROW_NUMBER() OVER(
ORDER BY PERFORMANCE DESC
) AS RN
FROM STUDENT


--2. Display dense rank of students based on SPI.

SELECT STDID ,SNAME , CITY ,PERFORMANCE ,BRANCH , DENSE_RANK() OVER
(ORDER BY SPI DESC) AS D_RANK
FROM STUDENT


--3. Display sequential number for each student record.

SELECT STDID ,SNAME , CITY ,PERFORMANCE ,BRANCH , ROW_NUMBER() OVER(
ORDER BY SPI DESC
) AS RN
FROM STUDENT 


--4. Display branch-wise rank of students.

SELECT STDID ,SNAME , CITY ,PERFORMANCE ,BRANCH , RANK() OVER
(PARTITION BY BRANCH
ORDER BY SPI DESC)
AS R
FROM STUDENT


--5. Display branch-wise dense ranking of students.

SELECT STDID ,SNAME , CITY ,PERFORMANCE ,BRANCH , DENSE_RANK() OVER
(PARTITION BY BRANCH
ORDER BY PERFORMANCE DESC) AS D_RANK
FROM STUDENT


--6. Display branch-wise sequential numbering of students.

SELECT STDID ,SNAME , CITY ,PERFORMANCE ,BRANCH , ROW_NUMBER() OVER(
PARTITION BY BRANCH
ORDER BY PERFORMANCE DESC
) AS RN
FROM STUDENT


--7. Display SNAME, Current SPI, Previous SPI and SPI Difference with previous student in ascending order of SPI.

SELECT SNAME , PERFORMANCE , LAG(PERFORMANCE) OVER(ORDER BY PERFORMANCE) AS PREVIOUS_SPI , (PERFORMANCE - (LAG(PERFORMANCE) OVER (ORDER BY PERFORMANCE))) AS DIFF
FROM STUDENT


--8. Display SNAME, Current SPI, Next SPI and SPI Difference with next student in descending order of SPI.

SELECT SNAME ,PERFORMANCE , LEAD(PERFORMANCE) OVER
(ORDER BY PERFORMANCE DESC) AS NEXT_SPI , (PERFORMANCE - (LEAD(PERFORMANCE) OVER (ORDER BY PERFORMANCE DESC))) AS DIFF
FROM STUDENT

--9. Display top 3 students based on SPI.

SELECT TOP 3 STDID ,SNAME , CITY , PERFORMANCE ,BRANCH , ROW_NUMBER() OVER(
ORDER BY SPI DESC
) AS RN
FROM STUDENT


--10. Display top 2 students from each branch.

SELECT TOP 2 STDID ,SNAME , CITY , PERFORMANCE ,BRANCH , ROW_NUMBER() OVER(
PARTITION BY BRANCH
ORDER BY PERFORMANCE DESC
) AS RN
FROM STUDENT

--Part – B:
--11. Display 5th highest SPI.

SELECT STDID ,SNAME , CITY , PERFORMANCE ,BRANCH , RN
FROM (SELECT STDID ,SNAME , CITY , PERFORMANCE ,BRANCH , ROW_NUMBER() OVER(
ORDER BY PERFORMANCE DESC
) AS RN
FROM STUDENT) AS E WHERE RN =5


--12. Display 6th highest SPI

SELECT STDID ,SNAME , CITY , PERFORMANCE ,BRANCH , RN
FROM (SELECT STDID ,SNAME , CITY , PERFORMANCE ,BRANCH , ROW_NUMBER() OVER(
ORDER BY PERFORMANCE DESC
) AS RN
FROM STUDENT) AS E WHERE RN =6


--13. Display students having same ranking.

SELECT SNAME ,
DENSE_RANK() OVER
(ORDER BY PERFORMANCE DESC) AS SAME_RANK
FROM (SELECT SNAME , DENSE_RANK() OVER
(ORDER BY SPI DESC) AS RANK_)
WHERE SNAME_RANK = RANK


--14. Display SNAME, Previous SPI, Current SPI and Next SPI based on ascending order of SPI.

SELECT SNAME ,PERFORMANCE , LAG(PERFORMANCE) OVER(ORDER BY PERFORMANCE) AS PREVIOUS_SPI , LEAD(PERFORMANCE) OVER
(ORDER BY SPI) AS NEXT_SPI 
FROM STUDENT


--15. Display topper of each branch.

SELECT SNAME , BRANCH , PERFORMANCE , ROW_NUMBER() OVER(
PARTITION BY BRANCH
ORDER BY PERFORMANCE DESC
) AS TOPPER
FROM STUDENT

----------------------------- PART – C -----------------------------

--16. DISPLAY STUDENTS WHOSE SPI IS GREATER THAN THE PREVIOUS STUDENT AND LESS THAN THE NEXT STUDENT.
SELECT SNAME, PERFORMANCE,
       LAG(PERFORMANCE) OVER(ORDER BY PERFORMANCE) AS PREVIOUS_SPI,
       LEAD(PERFORMANCE) OVER(ORDER BY PERFORMANCE) AS NEXT_SPI
FROM STUDENT
WHERE PERFORMANCE > LAG(PERFORMANCE) OVER(ORDER BY PERFORMANCE)
  AND PERFORMANCE < LEAD(PERFORMANCE) OVER(ORDER BY PERFORMANCE);

--17. DISPLAY BRANCH-WISE SECOND TOPPER STUDENTS.
SELECT STDID, SNAME, BRANCH, PERFORMANCE
FROM (
    SELECT STDID, SNAME, BRANCH, PERFORMANCE,
           ROW_NUMBER() OVER(PARTITION BY BRANCH ORDER BY PERFORMANCE DESC) AS RN
    FROM STUDENT
) AS SUB
WHERE RN = 2;

--20. DISPLAY STUDENTS WHOSE SPI DIFFERENCE WITH PREVIOUS STUDENT IS MAXIMUM.
SELECT STDID, SNAME, PERFORMANCE,
       PERFORMANCE - LAG(PERFORMANCE) OVER(ORDER BY PERFORMANCE) AS DIFF
FROM STUDENT
ORDER BY DIFF DESC
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;
